name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: mcr.microsoft.com/playwright:focal # Playwright Docker image
        options: --privileged # Allows Docker to run browsers in the container
        ports:
          - 8080:8080
        env:
          DISPLAY: :99.0
        volumes:
          - /dev/shm:/dev/shm # Shared memory optimization

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: |
          npx playwright test --headless
